version: 0.1
phases:
  pre_build:
    commands:
      - echo Prebuild ops
      - pip install -r /home/ec2-user/blogprojectdrf/requirements.txt
  build:
    commands:
      - echo Building the application 
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
